package appcli_test

import (
	appcli "bank-acc-interest/pkgs/app-cli"
	"bank-acc-interest/pkgs/transactions"
	"bytes"
	"io"
	"sync"
	"testing"
	"time"

	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestE2EInputTransactions(t *testing.T) {
	// NOTE: sleep for short duration so that app.Run() can write to buffer
	inputReader, inputWriter := io.Pipe()

	// NOTE: remember to run .Reset() after reading
	var outBuf bytes.Buffer

	app := appcli.NewAppCLI(inputReader, &outBuf, discardLogger)
	menu := appcli.InputTransactions{app}
	ctx := t.Context()

	var wg sync.WaitGroup
	var appErr, err error
	defer require.NoError(t, appErr)

	wg.Add(1)
	go func() {
		defer wg.Done()
		appErr = menu.Run(ctx)
	}()

	inputTxPrompt := `Please enter transaction details in <Date> <Account> <Type> <Amount> format
(or enter blank to go back to main menu):
`

	stutter()
	require.Contains(t, outBuf.String(), inputTxPrompt)
	outBuf.Reset()

	stutter()
	_, err = inputWriter.Write([]byte("20230626 AC001 W 100.00\n"))
	require.NoError(t, err)

	stutter()
	require.Contains(t, outBuf.String(), "Account: AC001\n| Date     | Txn Id      | Type | Amount |\n| 20230626 | 20230626-02 | W    | 100.00 |\n")
	outBuf.Reset()

	wg.Wait()
}

func TestNewTransactionFromString(t *testing.T) {
	t.Parallel()

	for _, tt := range []struct {
		name   string
		given  string
		expect transactions.Transaction
		err    error
	}{
		{
			name:  "Example from REQUIREMENTS.md",
			given: "20230626 AC001 W 100.00",
			expect: transactions.Transaction{
				Date:      time.Date(2023, time.June, 26, 0, 0, 0, 0, time.UTC),
				AccountID: "AC001",
				ID:        "",
				Type:      "W",
				Amount:    decimal.NewFromInt(100),
			},
			err: nil,
		},
		{
			name:   "Invalid Date format",
			given:  "20230626xxx AC001 W 100.00",
			expect: transactions.Transaction{},
			err:    appcli.ErrInvalidInput,
		},
		{
			name:  "Case Insensitive Type",
			given: "20230626 AC001 d 100.00",
			expect: transactions.Transaction{
				Date:      time.Date(2023, time.June, 26, 0, 0, 0, 0, time.UTC),
				AccountID: "AC001",
				ID:        "",
				Type:      "D",
				Amount:    decimal.NewFromInt(100),
			},
			err: nil,
		},
		{
			name:   "Amount must be > 0",
			given:  "20230626 AC001 d -100.00",
			expect: transactions.Transaction{},
			err:    appcli.ErrInvalidInput,
		},
		{
			name:   "2 DP precision",
			given:  "20230626 AC001 d 100.003",
			expect: transactions.Transaction{},
			err:    appcli.ErrInvalidInput,
		},
		{
			name:   "Missing Number of Tokens",
			given:  "20230626 AC001 W ",
			expect: transactions.Transaction{},
			err:    appcli.ErrInvalidInput,
		},
	} {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			have, err := appcli.NewTxFromString(tt.given)
			require.ErrorIs(t, err, tt.err)

			// NOTE: `ID` field is not generated by this function
			assert.Equal(t, tt.expect.Date, have.Date)
			assert.Equal(t, tt.expect.AccountID, have.AccountID)
			assert.Equal(t, tt.expect.Type, have.Type)
			assert.True(t, tt.expect.Amount.Equal(have.Amount))
		})
	}
}
